\name{bmhyd}
\alias{bmhyd}
%- Also NEED an '\alias' for EACH other topic documented here.
\title{
contour plots
}
\description{
Contour plots for the negative log likelihood function for pair of parameters among the parameter set.
Hybrid vigor \eqn{\beta}, heritability factor \eqn{h}, and hybrid variation \eqn{v_H}.
}

\usage{
bmhyd.contour(data, network)
}
%- maybe also 'usage' for other objects documented here.
\arguments{
  \item{data}{
a data vector containing species information (see Details).
}
  \item{network}{
a rooted phylogenetic network (see Details).
}
}
\details{This function generate the two dimensional contour plots for the negative log likelihood of the model. This function first evaluates the MLE estimates
\eqn{\hat{\mu}, \hat{\sigma}^2,hat{\beta},\hat{h},\hat{v}_H} and their standard errors. Then the contour plots is generated by the grid method.
For instance, for the contour plot of \eqn{\beta, v_H}, the domain \bold{D} is generated using \eqn{ [\hat{\beta}}- 2*se,\hat{\beta}}+ 2*se ] \times [\hat{v_H}}- 2*se,\hat{v_H}} 2*se  ] },
On each grid point, fixed value of \eqn{\beta, v_H} are determined by taking the interior point of the domian  \bold{D}, other three parameters are estimated through MLE approach and the negative log likelihood function
value is returned. Those negative log likelihood values collected from each grid point are then recorded into an array. The negative log likelihood array are then
transformed by taking the difference from the negative log likelihood value estimated from the full model. Finally the contour plot is
generate under the package \pkg{contour}.
}
\value{
 \item{contour plot}{generate three contour plot for \eqn{(\beta, v_H)}, (\beta,h), (h,v_H)}
}

\author{
Dwueng-Chwuan Jhwueng <djhwueng@nimbios.org>
}

\references{
Jhwueng D.C. and O'Meara B.C. 2012. \emph{A new comparative method for studying hybrid trait evolution using phylogenetic networks.}
}

\examples{
## A 9 taxa 2 hydbrid phylogenetic network in eNewick format.
network<-"(((1:0.35,2:0.35)10:0.5,(3:0.7,(4:0.45,(5:0.1,(6:0.1)13:0)12:0.35)
11:0.25)16:0.15)18:0.15,((13:0,7:0.1)14:0.55,(8:0.2,9:0.2)15:0.45)17:0.35)19:0;"
## Comparative data
data<-matrix(c( 16.00,12.00,16.00,23.00,18.00,18.00,25.00,20.00,14.00  ),ncol=1)
bmhyd.contour(data,network)
}
